[package]
name = "kmon"
version = "1.4.0"
description = "Linux kernel manager and activity monitor"
authors = ["orhun <orhunparmaksiz@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"
documentation = "https://github.com/orhun/kmon/blob/master/README.md"
homepage = "https://github.com/orhun/kmon"
repository = "https://github.com/orhun/kmon"
keywords = ["linux", "kernel", "module", "activity", "monitor"]
categories = ["command-line-utilities", "os"]
edition = "2018"

[dependencies]
clap = "2.33.0"
tui = "0.8.0"
termion = "1.5.5"
bytesize = "1.0.0"
unicode-width = "0.1.7"
enum-unitary = "0.4.2"
enum-iterator = "0.6.0"
clipboard = "0.5.0"
colorsys = "0.5.3"

[profile.dev]
opt-level = 0
debug = true

[profile.test]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
debug = false

[profile.bench]
opt-level = 3
debug = false
