name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t kmon .
      - name: Tag
        run: |
         docker tag kmon ${{ secrets.DOCKER_USERNAME }}/kmon:latest
         docker tag kmon docker.pkg.github.com/orhun/kmon/kmon:latest
      - name: Login (Docker Hub)
        run: echo ${{ secrets.DOCKER_PASSWORD }} |
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push (Docker Hub)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/kmon:latest
      - name: Login (Package Registry)
        run: echo ${{ secrets.GITHUB_TOKEN }} |
          docker login -u orhun docker.pkg.github.com --password-stdin
      - name: Push (Package Registry)
        run: docker push docker.pkg.github.com/orhun/kmon/kmon:latest
